### ISSUE TITLE
Disperse siblings moves cards to the past

### ISSUE THREAD

**Issue by szalejot** [open-spaced-repetition/fsrs4anki-helper#153]
Steps to reproduce:

- Make all daily reviews on some device without FSRS - like Ankidroid.
- Open desktop app with "Auto reschedule cards reviewed in other device after sync" and "Auto disperse siblings after sync and review" enabled.
- Some cards got rescheduled to have due date in the past.

Cards that appear as overdue after auto disperse siblings are in fact siblings of the cards that I reviewed today. Which is counter-productive because I am getting to review siblings of the cards already reviewed today - the opposite of what dispersing should aim for.

**Comment by L-M-Sherlock** [comment]
> * Some cards got rescheduled to have due date in the past.

Could you share the card info of these cards with me?

**Comment by szalejot** [comment]
Sure, how would you like me to share it? What exact info do you need?

**Comment by L-M-Sherlock** [comment]
The screenshots of these cards' info. For example: 

![image](https://github.com/open-spaced-repetition/fsrs4anki-helper/assets/32575846/a0900048-33c5-4a9d-9777-376e358c9acd)

**Comment by szalejot** [comment]
Sure, I will try to reproduce the issue today and will add info of the few examples later in the evening - Europe time.

**Comment by L-M-Sherlock** [comment]
By the way, I think this issue is hard to solve. Because Disperse siblings should respect the fuzz range. If the fuzz range is earlier than today, these siblings will always be overdue.

**Comment by szalejot** [comment]
What about a check, that if card is not due before dispersing then limit fuzz range, so it will not become due after dispersing?

**Comment by L-M-Sherlock** [comment]
> What about a check, that if card is not due before dispersing then limit fuzz range, so it will not become due after dispersing?

Good idea. I will consider it in the code.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11847039/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/5f6dabed01f21cf525bb803d0d18b27d359f13a5

It may alleviate the problem.

**Comment by szalejot** [comment]
Another approach would be to take in the dispersing not only due dates but also last review dates - it will make code possibly more complex and computational demanding, but should yield better results.
Example:
Note has 2 cards. Card-1 is due today and Card-2 due in 3 days.
I review Card-1 today and it will be due in 7 days. Dispersing kicks in and moves Card-2 to be due in 1 day instead of 3 days.
Does current disperse logic worked? Yes, because it increased due spread from 4 days to 6 days.
Is it better? Questionable, because without dispersing I would see sibling 3 days from today and after dispersing I will see it the next day.

**Comment by user1823** [comment]
> Another approach would be to take in the dispersing not only due dates but also last review dates

The current version (even the version currently on AnkiWeb) takes the last review date into account.

**Comment by szalejot** [comment]
Oh, I missed that. In such case commit https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/5f6dabed01f21cf525bb803d0d18b27d359f13a5 may make things better.

**Comment by L-M-Sherlock** [comment]
For more details about Disperse siblings, please see: https://github.com/open-spaced-repetition/fsrs4anki/issues/188#issuecomment-1510032739

**Comment by L-M-Sherlock** [comment]
I didn't test it practically. But, in the code, I found the following line:
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/3d19740c6d0afe18e3da9178215929b72b458f81/disperse_siblings.py#L263

This implies that the add-on uses the display of the answer as the trigger for dispersing siblings.

If it is the same as what I understand, this approach has three problems:
- Dispersal of siblings occurs before the card is actually answered. This means that
   - the last review date used for dispersing is not the same as the current date.
   - the due date of the card being answered is changed even before the card is answered.
- Dispersal of siblings can occur even if the card is not answered (if the user clicks "Show Answer" but doesn't rate the card).

A better approach would be to use `reviewer_did_answer_card` as the trigger. You can take help from the [Straight Rewards add-on](https://github.com/hgiesel/anki_straight_reward).

_Originally posted by @user1823 in https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/150#issuecomment-1604090758_

Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11847984/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/e1eb958c130a02825652a529bfe5bb73a5b98975

This patch disperses the siblings after answer the card.

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11848522/fsrs4anki-helper.zip)
Commit: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/bc32bc20f6d40bd75cd264f52b6c74c478c434bf

Fixed a potential bug.

**Comment by szalejot** [comment]
I've installed the add-on version from the previous comment. No instance of dispersing siblings into the past today.

**Comment by user1823** [comment]
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11848522/fsrs4anki-helper.zip)
> Commit: [bc32bc2](https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/bc32bc20f6d40bd75cd264f52b6c74c478c434bf)
> 
> Fixed a potential bug.

I tested this version. It works fine for me. However, I can't test the linked issue (cards moving to the past) because I never encountered it in the first place.

@szalejot, the auto-disperse after sync is working fine for me. I guess that you forgot to re-enable the auto-reschedule and auto-disperse after updating the add-on. Remember that the config is reset after every update of the add-on.

@Expertium, you might want to test this patch. With this patch, the siblings are dispersed after the card is answered and not after the answer is displayed. Also, the card that is being reviewed is not excluded from dispersal.

**Comment by Expertium** [comment]
> Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/11848522/fsrs4anki-helper.zip) Commit: [bc32bc2](https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/bc32bc20f6d40bd75cd264f52b6c74c478c434bf)
> 
> Fixed a potential bug.

Seems to be working fine.
